# -*- coding: utf-8 -*-
"""Task7_AutoFeatureSelector_Resolved.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYO9vPv9MPIfW-lHqyybCWQRrKwmww9u

# Task 7: AutoFeatureSelector Tool
## This task is to test your understanding of various Feature Selection methods outlined in the lecture and the ability to apply this knowledge in a real-world dataset to select best features and also to build an automated feature selection tool as your toolkit

### Use your knowledge of different feature selector methods to build an Automatic Feature Selection tool
- Pearson Correlation
- Chi-Square
- RFE
- Embedded
- Tree (Random Forest)
- Tree (Light GBM)

### Dataset: FIFA 19 Player Skills
#### Attributes: FIFA 2019 players attributes like Age, Nationality, Overall, Potential, Club, Value, Wage, Preferred Foot, International Reputation, Weak Foot, Skill Moves, Work Rate, Position, Jersey Number, Joined, Loaned From, Contract Valid Until, Height, Weight, LS, ST, RS, LW, LF, CF, RF, RW, LAM, CAM, RAM, LM, LCM, CM, RCM, RM, LWB, LDM, CDM, RDM, RWB, LB, LCB, CB, RCB, RB, Crossing, Finishing, Heading, Accuracy, ShortPassing, Volleys, Dribbling, Curve, FKAccuracy, LongPassing, BallControl, Acceleration, SprintSpeed, Agility, Reactions, Balance, ShotPower, Jumping, Stamina, Strength, LongShots, Aggression, Interceptions, Positioning, Vision, Penalties, Composure, Marking, StandingTackle, SlidingTackle, GKDiving, GKHandling, GKKicking, GKPositioning, GKReflexes, and Release Clause.
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as ss
from collections import Counter
import math
from scipy import stats

player_df = pd.read_csv("fifa19.csv")

numcols = ['Overall', 'Crossing','Finishing',  'ShortPassing',  'Dribbling','LongPassing', 'BallControl', 'Acceleration','SprintSpeed', 'Agility',  'Stamina','Volleys','FKAccuracy','Reactions','Balance','ShotPower','Strength','LongShots','Aggression','Interceptions']
catcols = ['Preferred Foot','Position','Body Type','Nationality','Weak Foot']

player_df = player_df[numcols+catcols]
player_df.head()

player_df = player_df[numcols+catcols]
traindf = pd.concat([player_df[numcols], pd.get_dummies(player_df[catcols])],axis=1)
features = traindf.columns

traindf = pd.concat([player_df[numcols], pd.get_dummies(player_df[catcols])],axis=1)
features = traindf.columns

traindf = traindf.dropna()

traindf = pd.DataFrame(traindf,columns=features)

y = traindf['Overall']>=87
X = traindf.copy()
del X['Overall']

X.head()

len(X.columns)

"""### Set some fixed set of features"""

feature_name = list(X.columns)
# no of maximum features we need to select
num_feats=30

"""## Filter Feature Selection - Pearson Correlation

### Pearson Correlation function
"""

# def cor_selector_mine(X, y, num_features):
#     # Your code goes here (Multiple lines)
#     corr_list= []

#     # calculating the correlation of each feature with respect to y
#     # using numpy method
#     for column in X.columns:
#         corr= np.corrcoef(X[column], y)[0][1]
#         # the corrcoef function will bring a 2x2 corr matrix
#         # in this case, so I pick the first value presenting the
#         # corr of the feature with respect to the target
#         # ([0][1], but could be [1][0] as well)

#         corr_list.append({
#             column: abs(float(corr)) if corr is not np.nan else 0
#         })

#     # sort based on the dictionary values
#     sorted_corr= sorted(
#         corr_list
#         , key= lambda x: abs(list(x.values())[0]) # sorting based on corr_list VALUES
#     )
#     # in the function above we use abs because for Pearson the most important thing is the magnitude of the correlation

#     # picking only the first num_features (from the end, since our list is already sorted)
#     final_select= sorted_corr[-num_features:]

#     # Your code ends here
#     return final_select,corr_support
#     #return sorted_corr

def corr_selector(X, y,num_feats):
    # Your code goes here (Multiple lines)
    cor_list= []
    feature_name= X.columns.tolist()

    # calculate the correlation with y for each feature
    for i in X.columns.tolist():
        corr= np.corrcoef(X[i], y)[0][1]
        cor_list.append(corr)

    # replace NaN with 0
    corr_list= [0 if np.isnan(i) else i for i in cor_list]

    # feature name
    corr_feature = X.iloc[:, np.argsort(np.abs(corr_list))[-num_feats:]].columns.tolist()

    # feature selection? (0 for not select, 1 for select)
    corr_support= [True if i in corr_feature else False for i in feature_name]
    # Your code ends here
    return corr_support, corr_feature

corr_support, corr_feature = corr_selector(X, y,num_feats)
print(str(len(corr_feature)), 'selected features')

"""### List the selected features from Pearson Correlation"""

corr_feature

"""## Filter Feature Selection - Chi-Sqaure"""

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.preprocessing import MinMaxScaler

"""### Chi-Squared Selector function
- This algorithm will return the most probably related features comparing their statistical association
- Basically the algorithm goes into the dataset and checks how different the target observed values are (related to one feature)
than the target expected values would be if there were no relationship at all
- It goes on each of those features and performs the computations, extracting in the end the ones with highest chi2 scores
![image.png](attachment:image.png)
"""

def chi_squared_selector(X, y, num_feats):
    # Your code goes here (Multiple lines)
    from sklearn.feature_selection import SelectKBest, chi2
    from sklearn.preprocessing import MinMaxScaler

    X_norm= MinMaxScaler().fit_transform(X)

    chi2_selector= SelectKBest(chi2, k= num_feats)
    chi2_selector.fit(X_norm, y)
    chi2_support= chi2_selector.get_support()
    chi2_feature= X.loc[:, chi2_support].columns.tolist()
    # Your code ends here
    return chi2_support, chi2_feature

chi2_support, chi2_feature = chi_squared_selector(X, y,num_feats)
print(str(len(chi2_feature)), 'selected features')

"""### List the selected features from Chi-Square"""

chi2_feature

"""## Wrapper Feature Selection - Recursive Feature Elimination
- These are called a *wrapper* feature selection algorithm because it actually selects the best set of features based on model's accuracy
- They keep re-testing until they find the combination set of features with the best measured accuracy
- One interesting part on all of this is that the wrapper can be any model as needed (so if we're dealing with a pure regression dataset
we can use a LinearRegression model... pure classification we can use LogisticRegression... and so on so forth)
    - So it depends on the use case... On each use case it will use the best metrics to find the best set of feature accordingly
"""

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler

"""### RFE Selector function"""

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler

def rfe_selector(X, y, num_feats):
    # Your code goes here (Multiple lines)

    rfe_selector= RFE(
        estimator= LogisticRegression(),
        n_features_to_select= num_feats,
        step= 10,
        verbose= 5
    )

    X_norm= MinMaxScaler().fit_transform(X)
    rfe_selector.fit(X_norm, y)

    rfe_support= rfe_selector.get_support()
    rfe_feature= X.loc[:, rfe_support].columns.tolist()
    # Your code ends here
    return rfe_support, rfe_feature

rfe_support, rfe_feature = rfe_selector(X, y,num_feats)
print(str(len(rfe_feature)), 'selected features')

"""### List the selected features from RFE"""

rfe_feature

"""## Embedded Selection - Lasso: SelectFromModel
- LASSO tries to make predictions while "charging" the model for having coefficients. Features that aren't contributing enough can have their coefficient driven all the way to zero, therefore resulting in a feature selection

- Just a few observations about Lasso:
    - Normally we apply it as out final model already (it's a linear regression as well, but traiend with penalty)
    - Or we can also use it to select features (as we are doing irght now), and then on those features we can apply the LinearRegression algorithm
"""

from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler

def embedded_log_reg_selector(X, y, num_feats):
    # Your code goes here (Multiple lines)
    X_norm= MinMaxScaler().fit_transform(X)

    lr_selector= SelectFromModel(
        LogisticRegression(l1_ratio= 1, solver= 'liblinear'),
        max_features= num_feats
        )
    lr_selector.fit(X_norm,y)

    lr_support= lr_selector.get_support()
    lr_feature= X.loc[:, lr_support].columns.tolist()

    # Your code ends here
    return lr_support, lr_feature

embedded_lr_support, embedded_lr_feature = embedded_log_reg_selector(X, y, num_feats)
print(str(len(embedded_lr_feature)), 'selected features')

embedded_lr_feature

"""## Tree based(Random Forest): SelectFromModel"""

from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier

def embedded_rf_selector(X, y, num_feats):
    # Your code goes here (Multiple lines)
    embedded_rf_selector= SelectFromModel(
        RandomForestClassifier(n_estimators= 100),
        max_features= num_feats
    )
    embedded_rf_selector.fit(X,y)

    embedded_rf_support = embedded_rf_selector.get_support()
    embedded_rf_feature = X.loc[:, embedded_rf_support].columns.tolist()
    # Your code ends here
    return embedded_rf_support, embedded_rf_feature

embedded_rf_support, embedded_rf_feature = embedded_rf_selector(X, y, num_feats)
print(str(len(embedded_rf_feature)), 'selected features')

embedded_rf_feature

"""## Tree based(Light GBM): SelectFromModel"""

from sklearn.feature_selection import SelectFromModel
from lightgbm import LGBMClassifier

def embedded_lgbm_selector(X, y, num_feats):
    # Your code goes here (Multiple lines)
    lgbmc= LGBMClassifier(
        n_estimators= 500,
        learning_rate= 0.05,
        num_leaves= 32,
        colsample_bytree=0.2,
        reg_alpha=3,
        reg_lambda=1,
        min_split_gain= 0.01,
        min_child_weight=40
    )

    embedded_lgbm_selector= SelectFromModel(lgbmc
                                           , max_features= num_feats
                                        )
    embedded_lgbm_selector.fit(X,y)

    embedded_lgbm_support= embedded_lgbm_selector.get_support()
    embedded_lgbm_feature= X.loc[:, embedded_lgbm_support].columns.tolist()
    # Your code ends here

    return embedded_lgbm_support, embedded_lgbm_feature

embedded_lgbm_support, embedded_lgbm_feature = embedded_lgbm_selector(X, y, num_feats)
print(str(len(embedded_lgbm_feature)), 'selected features')

embedded_lgbm_feature

"""## Putting all of it together: AutoFeatureSelector Tool"""

pd.set_option('display.max_rows', None)
# put all selection together
feature_selection_df = pd.DataFrame({'Feature':feature_name, 'Pearson':corr_support, 'Chi-2':chi2_support, 'RFE':rfe_support, 'Logistics':embedded_lr_support,
                                    'Random Forest':embedded_rf_support, 'LightGBM':embedded_lgbm_support})
# count the selected times for each feature
feature_selection_df['Total'] = feature_selection_df.drop(columns='Feature').sum(axis=1)

# display the top 100
feature_selection_df = feature_selection_df.sort_values(['Total','Feature'] , ascending=False)
feature_selection_df.index = range(1, len(feature_selection_df)+1)
feature_selection_df.head(num_feats)

feature_selection_df.iloc[:5]['Feature'].tolist()

"""## Can you build a Python script that takes dataset and a list of different feature selection methods that you want to try and output the best (maximum votes) features from all methods?"""

def preprocess_dataset(dataset_path):
    # Your code starts here (Multiple lines)
    player_df= pd.read_csv(f'{dataset_path}')

    numcols = ['Overall', 'Crossing','Finishing',  'ShortPassing',  'Dribbling','LongPassing', 'BallControl', 'Acceleration','SprintSpeed', 'Agility',  'Stamina','Volleys','FKAccuracy','Reactions','Balance','ShotPower','Strength','LongShots','Aggression','Interceptions']
    catcols = ['Preferred Foot','Position','Body Type','Nationality','Weak Foot']
    player_df = player_df[numcols+catcols]

    player_df = player_df[numcols+catcols]
    traindf = pd.concat([player_df[numcols], pd.get_dummies(player_df[catcols])],axis=1)
    features = traindf.columns

    traindf = pd.concat([player_df[numcols], pd.get_dummies(player_df[catcols])],axis=1)
    features = traindf.columns

    traindf = traindf.dropna()

    traindf = pd.DataFrame(traindf,columns=features)

    y = traindf['Overall']>=87
    X = traindf.copy()
    del X['Overall']

    num_feats=30

    # Your code ends here
    return X, y, num_feats

def autoFeatureSelector(dataset_path, methods=[]):
    # Parameters
    # data - dataset to be analyzed (csv file)
    # methods - various feature selection methods we outlined before, use them all here (list)

    # preprocessing
    X, y, num_feats = preprocess_dataset(dataset_path)

    # Run every method we outlined above from the methods list and collect returned best features from every method
    if 'pearson' in methods:
        cor_support, cor_feature = corr_selector(X, y,num_feats)
    if 'chi-square' in methods:
        chi_support, chi_feature = chi_squared_selector(X, y,num_feats)
    if 'rfe' in methods:
        rfe_support, rfe_feature = rfe_selector(X, y,num_feats)
    if 'log-reg' in methods:
        embedded_lr_support, embedded_lr_feature = embedded_log_reg_selector(X, y, num_feats)
    if 'rf' in methods:
        embedded_rf_support, embedded_rf_feature = embedded_rf_selector(X, y, num_feats)
    if 'lgbm' in methods:
        embedded_lgbm_support, embedded_lgbm_feature = embedded_lgbm_selector(X, y, num_feats)


    # Combine all the above feature list and count the maximum set of features that got selected by all methods
    #### Your Code starts here (Multiple lines)

    pd.set_option('display.max_rows', None)
    # put all selection together
    feature_selection_df = pd.DataFrame({'Feature':feature_name, 'Pearson':corr_support, 'Chi-2':chi2_support, 'RFE':rfe_support, 'Logistics':embedded_lr_support,
                                        'Random Forest':embedded_rf_support, 'LightGBM':embedded_lgbm_support})
    # count the selected times for each feature
    feature_selection_df['Total'] = feature_selection_df.drop(columns='Feature').sum(axis=1)

    # display the top 100
    feature_selection_df = feature_selection_df.sort_values(['Total','Feature'] , ascending=False)
    feature_selection_df.index = range(1, len(feature_selection_df)+1)

    best_features= feature_selection_df.iloc[:num_feats]['Feature'].tolist()
    #### Your Code ends here
    return best_features

best_features = autoFeatureSelector(dataset_path="fifa19.csv", methods=['pearson', 'chi-square', 'rfe', 'log-reg', 'rf', 'lgbm'])
best_features

"""### Last, Can you turn this notebook into a python script, run it and submit the python (.py) file that takes dataset and list of methods as inputs and outputs the best features"""

